### PR TITLE
Add npm installer

### PR DESCRIPTION
**Pull request by bobbypriambodo**
As stated in #84, here is the result of my fiddling with npm installer for `elm-format`. I'm drawing many examples from [`elm-platform` npm installers](https://github.com/elm-lang/elm-platform/tree/master/installers/npm). I'm putting the installer at `package/npm` directory (may be moved if you wanted to).

Some questions, though:
1. I was thinking of creating my own repo rather than forking and creating a dir in this repo's `package`, but decided not to just to keep it centralized. Should I have done that instead?
2. I still have no idea what to export for local npm installation and use by `require`. Will exporting the binary paths (like `elm-platform` does) be enough?
3. I've referred the publishing process to the npm official docs on the README (along with some notes on version bumping). Please tell me if I need to add something more.

I've tested this by running `npm install -g .` inside the `package/npm` directory and it successfully downloaded and installed `elm-format` to my global module. Not publishing it to npm yet since npm have a kind of [restrictive publishing policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy).

Kindly take a look? @avh4 @eeue56

### CODE REVIEW

**Comment by bobbypriambodo** [comment]
Sorry, this is still broken in Windows (`zlib` and `unzip` behaves differently). I'm still working on it.

**Comment by bobbypriambodo** [comment]
I think I've fixed the Windows problem, at least now it will point to the correct `.exe` file. Unfortunately I have no Windows machine to test this at the moment, can anyone check if it works?

**Comment by bobbypriambodo** [comment]
I can confirm that it works on Windows 10 using PowerShell (see screenshot below), while CMD runs `elm-format` just fine but is treating the `.16` in `elm-format-0.16` as an extension... Any idea on the expected behavior on Windows?

screen shot 2016-09-25 at 5 35 54 pm

**Comment by hastebrot** [comment]
This works on Ubuntu 16.04 (x64). Thanks.

~~~
$ hub checkout https://github.com/avh4/elm-format/pull/237
$ cd package/npm/
$ sudo npm install -g
$ which elm-format
/usr/bin/elm-format
~~~

(using `hub` to checkout your PR: https://hub.github.com/)

**Comment by felixbecker** [comment]
Hi, don't know if this is the right place to post my feedback on an issue.  
I got an issue with the npm elm-format installer on windows 7 with the gits MINGW64 bash. 

It seems that Windows or MINGW64 has a problem with executables without an extension. Since elm-format is a cmd file it doesn't work by executing `elm-format` but does successfully if you execute `elm-format.cmd`. But not really sure here.

if I execute `elm-format` without the extension (.cmd) I get the following message 
`/d/Users/TheUserIAm/AppData/Roaming/npm/elm-format: line 1: /node_modules/elm-format/binaries/elm-format: No such file or directory`. 
Only on gits MINGW64 bash on windows if I use the regular CMD it works.
Any thoughts here? (using elm-format for elm 0.18)

**Comment by bobbypriambodo** [comment]
@felixbecker Where did you get elm-format installer from? If it's from npm (i.e. via `npm i elm-format`), then I believe it should be @rtfeldman's implementation from #288. That PR is more recent and I think is the one that has @avh4's blessing. I'll wait a bit, but if there's no further instruction I'll close this PR.

**Comment by felixbecker** [comment]
Yes, I ran `npm install elm-format -g` should I post this topic somewhere else?

**Comment by avh4** [comment]
@felixbecker yes, can you continue this discussion on #288 

For your case, I would expect the binaries to be `elm-format.exe`, not `elm-format.cmd`.

**Comment by rtfeldman** [comment]
@felixbecker I suspect the problem is that the installer asks `node` what the current platform and architecture are, and fetches the appropriate binary. You're getting the Linux version instead of the Windows `.exe` file because it's self-reporting as Linux from `bash`.

Does that sound plausible?

**Comment by avh4** [comment]
Thanks for the detailed work on this!  I mostly went with the approach in https://github.com/avh4/elm-format/pull/288, but a took a couple small things from here.

**Pull request merged**
