### PR TITLE
update readme to include Homebrew installation

### PR DESCRIPTION
**Pull request by enilsen16**
Merge if & when Homebrew/homebrew#48624 is merged.

### CODE REVIEW

**Comment by avh4** [comment]
Thanks for starting the homebrew PR.  FYI, the release plan is: one more alpha release (0.3) to get feedback from elm-dev, then a beta release (0.4) to get feedback from elm-discuss, and then the stable 1.0 release.

**Comment by enilsen16** [comment]
Homebrew/homebrew-devel-only#41 was merged.

**Comment by rundis** [comment]
:clap:

**Comment by avh4** [comment]
Great, thanks!  

Can you advise on what will need to be done to keep homebrew updated when a new elm-format release is made?  (I expect the 0.3 release to be ready in 2-5 weeks.)

**Comment by enilsen16** [comment]
I have no problem updating it as releases are made...
But basically just fork `homebrew-devel-only` and then change the `link`, `version`, and `sha256` in the devel block of `elm-format.rb`. Homebrew has some more info [here](https://github.com/Homebrew/homebrew/blob/master/CONTRIBUTING.md)

When elm format is finally stable some reorganizing of the formula will need to happen.

**Pull request merged**
