### PR TITLE
Add a self-replacing binary for --ignore-scripts

### PR DESCRIPTION
**Pull request by rtfeldman**
Should fix https://github.com/avh4/elm-format/issues/378

### CODE REVIEW

**Comment by avh4** [comment]
Oh, interesting.  I think I'd like to make the binwrap pre-publish hook automatically create this wrapper so that it doesn't have to be manually created and updated.

Was jetpack blocked on this (or the binwrap PR) getting merged?

**Comment by rtfeldman** [comment]
> Was jetpack blocked on this (or the binwrap PR) getting merged?

Nope! I'd like for us to get to a point where we can `npm install` everything with `--ignore-scripts=true` and this would remove a blocker to that, but it's not urgent.

**Comment by rtfeldman** [comment]
Made a PR to `binwrap` to include instructions for doing this in the README: https://github.com/avh4/binwrap/pull/10

**Comment by avh4** [comment]
An alternate approach was taken by upgrading to binwrap@0.2.0 in https://github.com/avh4/elm-format/pull/519

**Pull request closed without merging**
