### PR TITLE
Change JetBrains plugin

### PR DESCRIPTION
**Pull request by klazuka**
The JetBrains plugin previously developed by @durkiewicz has been inactive for about a year now. And he [intends to remove it](https://github.com/durkiewicz/elm-plugin/issues/22#issuecomment-352651205) from the JetBrains plugin repository in favor of the new plugin that I wrote.

### CODE REVIEW

**Comment by klazuka** [comment]
Ping. I'd like to get this merged since the old plugin does not (and will not) support 0.19, whereas the new plugin supports both 18 and 19.

Thank you 🙏

**Comment by klazuka** [comment]
The next release of intellij-elm has out-of-the-box support for elm-format. I force-pushed a new commit with the updated instructions (however, the new version will not be released for a couple more days).

**Comment by klazuka** [comment]
Could someone please merge this? The link in the readme for IntelliJ currently points at a plugin that:

- no longer exists in the IntelliJ plugin repository
- doesn’t support Elm 0.19

**Comment by klazuka** [comment]
@avh4 can you help me with getting this merged? I just got a question on Slack from a user who was confused by the out-of-date instructions. Thank you.

**Comment by avh4** [comment]
Merged!  Sorry for missing this earlier.

**Pull request merged**
