### PR TITLE
Correct Visual Studio Code integration setting.

### PR DESCRIPTION
**Pull request by ptlawrence**
The VS Code setting was incorrect.

### CODE REVIEW

**Comment by avh4** [comment]
It seems this was a recent change to the plugin.  The setting recommended in the plugin README is now
```
"[elm]": {
    "editor.formatOnSave": true
}
```

I think it's **probably** better to recommend that instead of setting formatOnSave for all files.  What do you think?

**Comment by ptlawrence** [comment]
I agree with you. Please let me know what I need to do, if anything, to make that change. (Sorry, but I'm new to collaborating on projects in GitHub.  Do I need to adjust my edit, and then submit a new pull request?)

**Comment by avh4** [comment]
If you made the original PR vie the github web interface, it's probably easiest to make a new PR, and then close this one afterwards.

(If you made it by checking out the repo locally, then you can either amend and force-push the branch, add a commit to the branch, or make a new branch and a new PR.)

**Comment by ptlawrence** [comment]
I can't get VS Code (version 1.20.0) to accept that preference setting syntax you listed.  I also tried
{
   "elm.editor.formatOnSave" : true
}

as well, but that also failed.  I'm not sure what the correct syntax is for enabling only for Elm...

**Comment by rtfeldman** [comment]
@ptlawrence try upgrading vscode? 🤔  I've been using this successfully:

```
    "[elm]": {
        "editor.formatOnSave": true
    },
```

**Comment by ptlawrence** [comment]
Okay, it's working for me now.  I'll submit the new pull request and close out the original one.  Thank you both!

**Comment by ptlawrence** [comment]
Closing this, as PR #461 improves on it.

**Pull request closed without merging**
