### PR TITLE
fix #199: prevent file overwrite when file content wouldn't change af…

### LINKED ISSUE #199: Don't touch/rewrite the file if the contents will not change
This is to support IDEA/IntelliJ format-on-save (see https://github.com/avh4/elm-format/issues/182#issuecomment-224748604)

### PR DESCRIPTION
**Pull request by gyzerok**
…ter formatting

### CODE REVIEW

**Comment by gyzerok** [comment]
I'm quite stuck with where to find the right test cases which should be fixed. Can you help me with that?

**Comment by gyzerok** [comment]
It looks like I was able to solve an issue in a nice way. Also I've done some renaming to remove confusion about `inputFile`/`inputFilename` arguments as they flow through the functions.

Btw that was my first ever code in Haskell :)

**Comment by avh4** [comment]
Looks good.  

Can you please verify whether the copyright for your elm-format contributions is owned by you and state that you are licensing your contributions under the BSD-3-Clause license.

Please also make a new commit adding yourself to the LICENSE file (after Daniel Bachler).

Thanks!

**Comment by gyzerok** [comment]
Done!

**Comment by avh4** [comment]
Yes, just confirming in the discussion here is good.

Thanks!

Will merge once CI finishes.

**Comment by gyzerok** [comment]
Oh, it seems like I still need to confirm :)

I confirm my copyrights on this contribution.

**Comment by avh4** [comment]
Merged, thanks!

**Pull request merged**
