### PR TITLE
Formatting a file in place (#14)

### PR DESCRIPTION
**Pull request by Janiczek**
I have not done Haskell in a long time, so there are probably some code style changes you'll want me to do. (I'm particularly unsure about the `when` ... and maybe the definition of `isOutputEmpty` could use a `$`?

And it would probably make more sense for the `output` option to be `Maybe FilePath` instead of a `FilePath` that can be `""` ... if you want me to refactor it that way, I can try.

Otherwise the functionality is as promised:
```bash
./elm-format MyFile.elm # formats it in place, but doesn't empty it if there's a parse error
./elm-format MyFile.elm --output MyFile2.elm # creates MyFile2.elm, writes the result if successful or leaves empty if parse error
```

(No interactive warning yet.)

### CODE REVIEW

**Comment by avh4** [comment]
Looks pretty good.  Yes, let's use `Maybe FilePath`.  Also, can you try to add something to `tests/run_tests.sh` to cover the new functionality.  (Or if you can think of a good way to test this in haskell, that'd be okay too.)

**Comment by Janiczek** [comment]
OK this should be up to speed and ready to be merged. Then #15 could be (I hope) trivial.

**Comment by Janiczek** [comment]
Oh wait, the tests. Forgot about them.

**Comment by Janiczek** [comment]
Is it ready for merging now?

**Comment by avh4** [comment]
Looks great, I should be able to merge it tonight (PST)

**Comment by Janiczek** [comment]
I'll be able to work on #15 and #16 then. (CEST :) )

**Comment by avh4** [comment]
I made a couple minor changes when merging: https://github.com/avh4/elm-format/compare/06e2cda5413449e576f65d31d9c400f35179c7e7...c27324e746f8e5641f13bba473515f661ceec339

Great tests, btw.  Thanks!

**Pull request merged**
