### PR TITLE
Allow building on Linux ARM64

### PR DESCRIPTION
**Pull request by tfausak**
This would address #714 and #765. It's similar to #769. 

These changes allow `elm-format` to be built on an ARM64 (AArch64) Linux machine. I have tested them with AMD64 (x86-64) as well, which continues to work as expected.

### CODE REVIEW

**Comment by ismaelga** [comment]
Bumped into the same issue. This PR seems legit.
Thanks! Hope it gets merged

**Comment by avh4** [comment]
Huh, github seems confused about the list of commits after I fixed the merge conflicts here.  :shrug: 

Merging.

**Comment by avh4** [comment]
Thanks!  This is on `main` branch now.  I haven't set up linux aarch64 CI yet, so lmk if there's still any problems.

**Comment by jsynacek** [comment]
Awesome, thanks a lot! Would you mind releasing a new version so that the builds show in the release and also in the npm archives?

**Comment by avh4** [comment]
The release is tracked here: https://github.com/avh4/elm-format/milestone/31

Basically I have to do a test run of the new npm publishing process, then get linux-aarch64 binaries to build on CI, then take a look at building musl binaries, and then do the release. 🤞

**Pull request merged**
