### PR TITLE
Update to ghc-9.0.2

### PR DESCRIPTION
**Pull request by avh4**

### CODE REVIEW

**Comment by arrowd** [comment]
Is there ETA for a new release with this change in?

**Comment by avh4** [comment]
> Is there ETA for a new release with this change in?

I merged this to try to build darwin-arm64 binaries on CI, but it turns out that there's still not going to be a way to do that yet.

Is there there something else that releasing this change would fix for you?

**Comment by arrowd** [comment]
Ultimately, my goal is to package `elm-format` for FreeBSD, while updating GHC to 9.2.2: https://github.com/freebsd/freebsd-ports-haskell/issues/53

**Comment by avh4** [comment]
Ah, okay.  My plan is to wait for https://github.com/avh4/elm-format/pull/769 to get cleaned up and merged, and then see if there's news on how soon ghc-9.4 will be released.  ghc-9.2.x has issues on Windows, so I'd like to update to ghc-9.4 asap.  Once it's decided if I'm going to do that now or not, then I'm planning to do a new release which will also include official linux-aarch64 binaries for the first time.

I'm not really sure on a timeline yet--somewhere between weeks and months.  Is there a particular timeline you were hoping for?

**Comment by arrowd** [comment]
Not really, I'm fine with marking the package broken for a while.

**Pull request merged**
